---
name: Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
          path: rtl_433_win


      # WINDOWS
      - name: Install dependencies
        shell: pwsh
        run: |
          cd ..
          Invoke-WebRequest -Uri "https://github.com/winterrace/librtlsdr/releases/download/0.6.0_upd/librtlsdr_0.6.0_win64_2019-08-19.zip" -OutFile librtlsdr_0.6.0_win64_2019-08-19.zip
          &7z x librtlsdr_0.6.0_win64_2019-08-19.zip -ortl-sdr
          Remove-Item librtlsdr_0.6.0_win64_2019-08-19.zip
          dir rtl-sdr
        
          
      - name: Build (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
            call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
            dir
            mkdir build
            cd build
            cmake  -DENABLE_RTLSDR=ON -G "Visual Studio 16 2019" -A x64 -DCMAKE_VERBOSE_MAKEFILE=true -DCMAKE_CONFIGURATION_TYPES=Release ..

            cmake --build . --config Release
            
        shell: cmd
